
services:
  backend:
    build: .
    container_name: api
    networks: [app-net]
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./pom.xml
    environment:
      AWS_REGION: us-east-1
      AWS_SHARED_CREDENTIALS_FILE: /home/spring/.aws/credentials
      AWS_CONFIG_FILE: /home/spring/.aws/config
    volumes:
      - C:\Users\calve\.aws:/home/spring/.aws:ro

  frontend:
    build: ./ui
    container_name: web
    ports:
      - "80:80"
    depends_on: [backend]
    networks: [app-net]
    develop:
      watch:
        - action: rebuild
          path: ./ui/src
        - action: rebuild
          path: ./ui/package.json




networks:
  app-net: {}
